### ISSUE TITLE
password recovery

### ISSUE THREAD

**Issue by faregon** [Ellmor/CoolGroupNameCMS#25]
can you recover password if requested by user or just change through crud ?

**Comment by faregon** [comment]
can you recover password if requested by user or just change through crud ?

**Comment by ldaine** [comment]
I think the admin should have control over all the users (also passwords). Not a real life scenario though. :) 
Otherwise the user should be able to change the password based on their email. As usually in websites when the user enters email, a link is send to their emails and by following the link user can access the form where to change the password (that will take time to implement though).

**Comment by ldaine** [comment]
Password recovery through Email - work in Progress
